// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALhC9hmQuzzRXSziyXZbjOl_wmSPNOsD0',
    appId: '1:587248508057:web:9fc7df0b29b9e6e7b92c08',
    messagingSenderId: '587248508057',
    projectId: 'cutomerprod',
    authDomain: 'cutomerprod.firebaseapp.com',
    storageBucket: 'cutomerprod.appspot.com',
    measurementId: 'G-HK5BBXKLJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWePplCecwxpyGpBJhlvSH-wvt3-1Gd9I',
    appId: '1:587248508057:android:a9f6b7dfad98e693b92c08',
    messagingSenderId: '587248508057',
    projectId: 'cutomerprod',
    storageBucket: 'cutomerprod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo2JtTFHuVrGgSR6vN_rhdhlPxIXzEv7A',
    appId: '1:587248508057:ios:05e66437c5cac899b92c08',
    messagingSenderId: '587248508057',
    projectId: 'cutomerprod',
    storageBucket: 'cutomerprod.appspot.com',
    androidClientId: '587248508057-mshug29ih4i32c16l72ualcst3jtp1un.apps.googleusercontent.com',
    iosClientId: '587248508057-cdt4tj2ld95701l4tc6na6fbvqe6l5nc.apps.googleusercontent.com',
    iosBundleId: 'com.gic.customerProductManagementSystem',
  );
}
